import type { Metadata } from "next";
import "./globals.css";
import "@tabler/icons-webfont/dist/tabler-icons.min.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const optionData = await fetch(
    "http://localhost:3000/api/option?optionName=bg-image",
    {
      cache: "no-store",
    }
  );
  const data = await optionData.json();
  const bg = data.optionValue || "";
  return (
    <html lang="zh-tw">
      <body>
        <div
          className="bg-cover bg-center h-screen"
          style={{ backgroundImage: `url('${bg}')` }}
        >
          <main className="md:container md:mx-auto">{children}</main>
        </div>
      </body>
    </html>
  );
}
